import { isRateLimited, clientKeyFor } from "../_lib/rateLimit.js";
import { requireAdminOrFlag } from "../_lib/featureFlags.js";
import { withConnection, friendlyConnectionError } from "../_lib/migration/mssqlClient.js";
import { splitQueries, parseQuery } from "../_lib/migration/parseQuery.js";
import { buildTableScript, buildProcScript } from "../_lib/migration/buildInsert.js";
import { resolveTables } from "../_lib/migration/resolveTables.js";

const MAX_QUERIES = 50;
const MAX_TOTAL_QUERY_LENGTH = 200_000;

function validateCreds(creds, label) {
  const { server, database, username, password, port } = creds || {};
  if (
    typeof server !== "string" || !server.trim() ||
    typeof database !== "string" || !database.trim() ||
    typeof username !== "string" || !username.trim() ||
    typeof password !== "string" || !password
  ) {
    return { error: `${label}: server, database, username, and password are all required.` };
  }
  if (port !== undefined && port !== "" && Number.isNaN(Number(port))) {
    return { error: `${label}: port must be a number.` };
  }
  return { creds: { server: server.trim(), database: database.trim(), username: username.trim(), password, port } };
}

function validateBody(body) {
  const { source, target, queries, includeDelete, includeIdentityInsert } = body || {};

  const sourceValidated = validateCreds(source, "Source database");
  if (sourceValidated.error) return { error: sourceValidated.error };

  let targetCreds = null;
  if (target) {
    const targetValidated = validateCreds(target, "Target database");
    if (targetValidated.error) return { error: targetValidated.error };
    targetCreds = targetValidated.creds;
  }

  if (!Array.isArray(queries) || queries.length === 0) {
    return { error: "At least one query is required." };
  }
  if (queries.length > MAX_QUERIES) {
    return { error: `Too many queries — max ${MAX_QUERIES} per run.` };
  }
  const totalLength = queries.reduce((sum, q) => sum + (typeof q === "string" ? q.length : 0), 0);
  if (totalLength > MAX_TOTAL_QUERY_LENGTH) {
    return { error: "Combined query text is too large." };
  }
  if (queries.some((q) => typeof q !== "string" || !q.trim())) {
    return { error: "Invalid query in list." };
  }

  return {
    source: sourceValidated.creds,
    target: targetCreds,
    queries,
    includeDelete: includeDelete !== false,
    includeIdentityInsert: includeIdentityInsert !== false,
  };
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed." });
  }

  if (isRateLimited(`migration-generate:${clientKeyFor(req)}`, 10)) {
    return res.status(429).json({ error: "Too many requests — please slow down." });
  }

  const session = await requireAdminOrFlag(req, res, "migrationGenerator");
  if (!session) return;

  const validated = validateBody(req.body);
  if (validated.error) {
    return res.status(400).json({ error: validated.error });
  }

  const parsedQueries = [];
  for (const queryText of validated.queries) {
    const parsed = parseQuery(queryText);
    if (parsed.error) {
      return res.status(400).json({ error: parsed.error });
    }
    parsedQueries.push(parsed);
  }

  try {
    const tables = await withConnection(validated.source, async (sourcePool) => {
      if (validated.target) {
        return withConnection(validated.target, (targetPool) =>
          resolveTables(sourcePool, targetPool, parsedQueries),
        );
      }
      return resolveTables(sourcePool, null, parsedQueries);
    });

    const sections = tables.map((t) =>
      t.isProc
        ? buildProcScript(t)
        : buildTableScript({
            ...t,
            includeDelete: validated.includeDelete,
            includeIdentityInsert: validated.includeIdentityInsert,
          }),
    );

    const header = [
      "-- ============================================================",
      "-- Generated by DevToolKit Migration Generator",
      "-- Each table below runs inside its own transaction: if any",
      "-- statement for that table fails, its changes are rolled back",
      "-- automatically and the error is re-thrown (script execution",
      "-- stops there). Tables already committed before the failure",
      "-- are NOT affected — review the failed table, fix the issue,",
      "-- and re-run just that section if needed.",
      "-- ============================================================",
      "",
    ].join("\n");

    return res.status(200).json({ script: header + sections.join("\n\n") });
  } catch (err) {
    if (err.userFacing) {
      return res.status(400).json({ error: err.message });
    }
    console.error("Migration generate failed:", err.message);
    return res.status(400).json({ error: friendlyConnectionError(err) });
  }
}
